version: '3.9'

services:
  app:
    image: maven:3.8.6-eclipse-temurin-11-alpine
    working_dir: /usr/src/app
    command: mvn spring-boot:run -Dspring-boot.run.profiles=dev
    ports:
      - 8080:8080
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DATABASE=${MONGO_DATABASE}
    networks:
      - appnet
    volumes:
      - maven-vol:/root/.m2
      - .:/usr/src/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - 27017:27017 # for debugging only
    environment:
      - MONGO_DB_USERNAME=${MONGO_USERNAME}
      - MONGO_DB_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DB_DATABASE=${MONGO_DATABASE}
    networks:
      - appnet
    volumes:
      - mongodb-vol:/data/db

networks:
  appnet: {}

volumes:
  maven-vol: {}
  mongodb-vol: {}